
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApiDAL.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_ExperienceDetails
{

    public int ID { get; set; }

    public Nullable<int> UserID { get; set; }

    public string JobTitle { get; set; }

    public string EmployerName { get; set; }

    public string Description { get; set; }

    public Nullable<System.DateTime> JoinDate { get; set; }

    public Nullable<System.DateTime> EndDate { get; set; }

    public Nullable<bool> Is_CurrentJob { get; set; }



    public virtual Tbl_User Tbl_User { get; set; }

}

}
