//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User
    {
        public int UserID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string UserEmail { get; set; }
        public string PassWord { get; set; }
        public string PhoneNumber { get; set; }
        public string ProfileImgPath { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<bool> SmsActive { get; set; }
        public Nullable<bool> EmailActive { get; set; }
        public Nullable<bool> AccountActive { get; set; }
    }
}
