//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_UserSocialProfile
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> SocialMediaID { get; set; }
        public string Activity { get; set; }
        public string ProfileURL { get; set; }
    }
}
