//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Job
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> JobTypeID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string JobDescription { get; set; }
        public string JobLocation { get; set; }
        public Nullable<decimal> MinExperienceRequired { get; set; }
        public Nullable<decimal> MaxExperienceRequired { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
