
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApiDAL.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_Job
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tbl_Job()
    {

        this.Tbl_JobActivity = new HashSet<Tbl_JobActivity>();

        this.Tbl_JobSkill = new HashSet<Tbl_JobSkill>();

        this.Tbl_UserJob = new HashSet<Tbl_UserJob>();

    }


    public int ID { get; set; }

    public Nullable<int> UserID { get; set; }

    public Nullable<int> JobTypeID { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string JobDescription { get; set; }

    public string JobLocation { get; set; }

    public Nullable<decimal> MinExperienceRequired { get; set; }

    public Nullable<decimal> MaxExperienceRequired { get; set; }

    public Nullable<System.DateTime> ExpireDate { get; set; }

    public Nullable<bool> IsActive { get; set; }



    public virtual Tbl_JobType Tbl_JobType { get; set; }

    public virtual Tbl_User Tbl_User { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tbl_JobActivity> Tbl_JobActivity { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tbl_JobSkill> Tbl_JobSkill { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tbl_UserJob> Tbl_UserJob { get; set; }

}

}
