//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SeekerProfile
    {
        public int SeekerProfileID { get; set; }
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<decimal> CurrentSalary { get; set; }
        public Nullable<decimal> ExpectedSalary { get; set; }
        public string Introduction { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public string ResumePath { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Gender { get; set; }
    
        public virtual Tbl_Currency Tbl_Currency { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
