
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApiDAL.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_UserLog
{

    public int UserID { get; set; }

    public Nullable<System.DateTime> LastLoginDate { get; set; }

    public Nullable<System.DateTime> LastJobApplyDate { get; set; }

}

}
