
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApiDAL.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_EmployerProfile
{

    public int ID { get; set; }

    public Nullable<int> UserID { get; set; }

    public Nullable<int> IndustryId { get; set; }

    public string EmployerName { get; set; }

    public string CompanyDescription { get; set; }

    public Nullable<System.DateTime> EstablishmentDate { get; set; }

    public string WebsiteURL { get; set; }



    public virtual Tbl_EmployerIndustry Tbl_EmployerIndustry { get; set; }

    public virtual Tbl_User Tbl_User { get; set; }

}

}
